name = "Kueso Cheese Pack"
author = "Kueso & Ampflower"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ffabc578cf05462fb11ba733b9f875b49586fb008021efb1c32a8ab000adf90"

[versions]
minecraft = "1.19.2"
quilt = "0.17.8"
